spring:
  application:
    name: event-scheduler
  datasource:
    url: jdbc:postgresql://localhost:5432/event-scheduler
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
# Hibernate JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
#    show-sql: true

